mess/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^rating/', include('rating.urls', namespace='rating')),
]

rating/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^start/', views.StartView.as_view(), name='start'),
    url(r'^read/', views.ReadView.as_view(), name='read'),
    url(r'^rating/', views.RatingView.as_view(), name='rating'),
]

rating/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.exceptions import ValidationError
import constants

# Create your models here.

class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True, blank=True)
	rollno = models.CharField(max_length=20, unique=True)
	name = models.CharField(max_length=100)
	resident_hostel = models.CharField(max_length=20, choices=constants.hostels)
	subscribed_hostel = models.CharField(max_length=20, choices=constants.hostels)

	def pretty_name(self):
		if self.name=="" or self.name is None:
			return "New User"+"("+self.rollno+")"
		else: 
			return self.name
	pretty_name.short_description = "Name"





def validate_ratingrange(value):
	if value < constants.rating_low or value > constants.rating_high:
		raise ValidationError(
			'%(value)s is out of bound',
			params={'value': value},
		)

class Activity(models.Model):
	timestamp = models.DateTimeField(auto_now_add=True, unique=True)
	profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
	hostel = models.CharField(max_length=20, choices=constants.hostels)
	
	cat_and_punct =   models.IntegerField("Catering and Punctuality" , validators=[validate_ratingrange])
	cleanliness   =   models.IntegerField("Cleanliness"              , validators=[validate_ratingrange])
	breakfast     =   models.IntegerField("Breakfast"                , validators=[validate_ratingrange])
	lunch         =   models.IntegerField("Lunch"                    , validators=[validate_ratingrange])
	dinner        =   models.IntegerField("Dinner"                   , validators=[validate_ratingrange])

	def get_profile_name(self):
		return str(self.profile.name)
	get_profile_name.short_description = "Profile Name"

	class Meta:
		verbose_name="Activity"
		verbose_name_plural="Activities"

rating/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.views import View
from django.contrib.auth import get_user_model, authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Profile, Activity
import constants
from django.db import IntegrityError
import datetime
from mess import settings

def get_card(request):
	try:
		from MFRC522python import util
		try:
			data = util.readcard(constants.read_timeout)
			if data and len(data)==2:
				#Convert rfid from four numbers in the range 0-255
				#To a 8 digit hex number
				rfid = [format(i, 'x') for i in data[0]] #format(n,'x') converts n to hexadecimal
				rfid = ''.join(rfid)
				rollno = data[1]
				return (rfid, rollno)
			else:
				messages.error(request, "Could not read card. Try again later.")
		except: #Any kind of exception
			messages.error(request, "Error while reading card. Try once more.")
	except: #Not running on R-Pi
		return (None, None)

# Create your views here.

class ReadView(View):
	def get(self, request, *args, **kwargs):
		#Logout if logged in
		if request.user.is_authenticated: 
			logout(request)

		#Try to read card
		card = get_card(request)
		storage = list(messages.get_messages(request))
		if len(storage)!=0:
			return render(request, 'rating/error.html')
		else:
			(rfid,rollno) = card
		#Purely for testing
		if settings.DEBUG==True and rfid is None and rollno is None:
			rfid = request.GET.get('rfid')
			rollno = request.GET.get('rollno')

		#Search for card in Users
		try:
			user = User.objects.get(username=rollno)
			try:
				profile = user.profile
			except Profile.DoesNotExist:
				try:
					profile = Profile.objects.get(rollno=rollno)
					profile.user = user
					profile.save()
				except Profile.DoesNotExist:
					messages.error(request, "HAB Profile does not exist for roll number : "+rollno)
					return render(request, 'rating/error.html')
		#Create User
		except User.DoesNotExist: 
			user = User.objects.create_user(username=rollno,password=rfid)
			user.save()
			try:
				profile = Profile.objects.get(rollno=rollno)
				profile.user = user
				profile.save()
			except Profile.DoesNotExist:
				messages.error(request, "HAB Profile does not exist for roll number : "+rollno)
				return render(request, 'rating/error.html')

		#Validate User
		if not user.check_password(rfid): 
			messages.error(request, "Roll Number or RFID incorrect")
			return render(request, 'rating/error.html')
		#Validate Profile
		try:
			profile.full_clean()
		except Exception as e:
			messages.error(request, "Profile Validation Error")
			for (key,value) in e.message_dict.iteritems():
				key = key.replace("_"," ")
				key = key.title()
				for item in value:
					messages.error(request, key + " : " + item)
			return render(request, 'rating/error.html')
		#Check if user is giving feedback at his subscribed_hostel
		if profile.subscribed_hostel != constants.current_hostel:
			messages.error(request, "You are giving feedback in wrong hostel. Please visit "+profile.subscribed_hostel+" to give your feedback.")
			return render(request, 'rating/error.html')
		#Check if user already gave feedback for this month
		temp = list(Activity.objects.filter(profile=profile))
		temp = [i.timestamp.month for i in temp]
		if datetime.datetime.now().month in temp:
			messages.error(request, "You have already given feedback for this month. Come back next month :D")
			return render(request, 'rating/error.html')


		#Login the user
		login(request, user)

		#Redirect to Rating View
		return HttpResponseRedirect(reverse('rating:rating'))





class RatingView(View):
	def get(self, request, *args, **kwargs):
		if request.user.is_authenticated: 
			return render(request, 'rating/submitrating.html')
		else:
			messages.error(request, "You are not authorized to view this page")
			return render(request, 'rating/error.html')

	def post(self, request, *args, **kwargs):
		if request.user.is_authenticated:
			#Get the data to be saved
			cat_and_punct  =   request.POST.get("catering_and_punctuality")
			cleanliness    =   request.POST.get("cleanliness")
			breakfast      =   request.POST.get("breakfast")
			lunch          =   request.POST.get("lunch")
			dinner         =   request.POST.get("dinner")
			hostel = request.user.profile.subscribed_hostel

			#Save it in activity
			temp = Activity(
				profile=request.user.profile, 
				cat_and_punct=cat_and_punct, 
				cleanliness=cleanliness,
				breakfast=breakfast,
				lunch=lunch,
				dinner=dinner,
				hostel=hostel
				)
			#Validate Activity
			try:
				temp.full_clean()
				temp.save()
				#Logout the user
				logout(request)
				#Render a thank you page
				return render(request, 'rating/thankyou.html')
			except Exception as e:
				messages.error(request, "Activity Validation Error")
				for (key,value) in e.message_dict.iteritems():
					key = key.replace("_"," ")
					key = key.title()
					for item in value:
						messages.error(request, key + " : " + item)
				return render(request, 'rating/error.html')			
		else:
			messages.error(request, "You are not authorized to access this")
			return render(request, 'rating/error.html')





class StartView(View):
	def get(self, request, *args, **kwargs):
		return render(request, 'rating/start.html')

rating/templates/rating/base.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
	<title>{% block title %}{% endblock %}</title>
	<!-- Stylesheets -->
	<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
	{% block css %}{% endblock %}
	<!-- Javascript -->
	<script src="{% static 'jquery/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
	{% block js %}{% endblock %}
	<style>
	.navbar-brand
	{
	    position: absolute;
	    width: 100%;
	    left: 0;
	    text-align: center;
	    margin:0 auto;
	}
	.paginate
	{
		min-height: 100vh;
		height: 100vh;
	}
	</style>
</head>

<body>
<!--
 	<nav class="navbar navbar-inverse navbar-static-top">
		<div class="container">
			<div class="navbar-header">
				<a class="navbar-brand align-middle" href="">Mess Rating</a>
			</div>
		</div>
	</nav>
 -->
	{% block content %}{% endblock %}
</body>
</html>

rating/templates/rating/error.html
{% extends "rating/base.html" %}

{% block title %}Mess Rating{% endblock %}

{% block css %}{% endblock %}

{% block js %}
	<script type="text/javascript">
		$( document ).ready(function() {
			setTimeout(function(){ window.location.href="{% url 'rating:start' %}" }, 4000);
		});
	</script>
{% endblock %}

{% block content %}
    <div class="container" style="padding-top:50px; text-align:center;">
        <h3>Sorry, An Error Occurred</h3>
        
        <h3><strong><u>Details</u></strong></h3>
        
        <h3 style="color: red">
		{% if messages %}
			{% for message in messages %}
				{{ message }}<br/>
			{% endfor %}
		{% endif %}
		</h3>

		<h3>Redirecting. Please wait.</h3>
    </div>
{% endblock %}

rating/templates/rating/start.html
{% extends "rating/base.html" %}

{% block title %}Mess Rating{% endblock %}

{% block css %}{% endblock %}

{% block js %}{% endblock %}

{% block content %}
    <div class="container" style="padding-top:140px; text-align:center;">
        <a type="button" class="btn btn-block btn-lg btn-success" href="{% url 'rating:read' %}">Start</a>
    </div>
{% endblock %}

rating/templates/rating/submitrating.html
{% extends "rating/base.html" %}

{% load static %}

{% block title %}Mess Rating{% endblock %}

{% block css %}{% endblock %}

{% block js %}
<script src="{% static 'rating/smooth_scroll.js' %}"></script>
{% endblock %}

{% block content %}
	<div class="container paginate" style="padding-top: 90px; padding-bottom: 90px;text-align:center;">
		<h2>
			{% if request.user.is_authenticated %}
				Welcome {{ request.user.profile.name }}
			{% endif %}
		</h2>
		<a class="btn btn-lg btn-block btn-success" href="#catering_and_punctuality">Continue</a>
	</div>

	<form method="post" action="{% url 'rating:rating' %}">
		
		{% csrf_token %}
		
		<div class="container paginate" style="padding-top: 70px; padding-bottom: 70px; text-align:center;" id="catering_and_punctuality">
			<h2>
				Catering and Punctuality
			</h2>
			<div class="btn-grp" data-toggle="buttons">
				<label class="btn btn-lg btn-primary">
					<input type="radio" name="catering_and_punctuality" value="0">0
				</label>
				<label class="btn btn-lg btn-primary">
					<input type="radio" name="catering_and_punctuality" value="1">1
				</label>
				<label class="btn btn-lg btn-primary">
					<input type="radio" name="catering_and_punctuality" value="2">2
				</label>
				<label class="btn btn-lg btn-primary active">
					<input type="radio" name="catering_and_punctuality" value="3" checked>3
				</label>
				<label class="btn btn-lg btn-primary">
					<input type="radio" name="catering_and_punctuality" value="4">4
				</label>
				<label class="btn btn-lg btn-primary">
					<input type="radio" name="catering_and_punctuality" value="5">5
				</label>
			</div>
			<br/>
			<a class="btn btn-lg btn-block btn-success" href="#cleanliness">Continue</a>
		</div>

		<div class="container paginate" style="padding-top: 70px; padding-bottom: 70px; text-align:center;" id="cleanliness">
			<h2>
				Cleanliness
			</h2>
			<div class="btn-grp" data-toggle="buttons">
				<label class="btn btn-lg btn-primary">
					<input type="radio" name="cleanliness" value="0">0
				</label>
				<label class="btn btn-lg btn-primary">
					<input type="radio" name="cleanliness" value="1">1
				</label>
				<label class="btn btn-lg btn-primary">
					<input type="radio" name="cleanliness" value="2">2
				</label>
				<label class="btn btn-lg btn-primary active">
					<input type="radio" name="cleanliness" value="3" checked>3
				</label>
				<label class="btn btn-lg btn-primary">
					<input type="radio" name="cleanliness" value="4">4
				</label>
				<label class="btn btn-lg btn-primary">
					<input type="radio" name="cleanliness" value="5">5
				</label>
			</div>
			<br/>
			<a class="btn btn-lg btn-block btn-success" href="#breakfast">Continue</a>
		</div>

		<div class="container paginate" style="padding-top: 70px; padding-bottom: 70px; text-align:center;" id="breakfast">
			<h2>
				Breakfast
			</h2>
			<div class="btn-grp" data-toggle="buttons">
				<label class="btn btn-lg btn-primary">
					<input type="radio" name="breakfast" value="0">0
				</label>
				<label class="btn btn-lg btn-primary">
					<input type="radio" name="breakfast" value="1">1
				</label>
				<label class="btn btn-lg btn-primary">
					<input type="radio" name="breakfast" value="2">2
				</label>
				<label class="btn btn-lg btn-primary active">
					<input type="radio" name="breakfast" value="3" checked>3
				</label>
				<label class="btn btn-lg btn-primary">
					<input type="radio" name="breakfast" value="4">4
				</label>
				<label class="btn btn-lg btn-primary">
					<input type="radio" name="breakfast" value="5">5
				</label>
			</div>
			<br/>
			<a class="btn btn-lg btn-block btn-success" href="#lunch">Continue</a>
		</div>

		<div class="container paginate" style="padding-top: 70px; padding-bottom: 70px; text-align:center;" id="lunch">
			<h2>
				Lunch
			</h2>
			<div class="btn-grp" data-toggle="buttons">
				<label class="btn btn-lg btn-primary">
					<input type="radio" name="lunch" value="0">0
				</label>
				<label class="btn btn-lg btn-primary">
					<input type="radio" name="lunch" value="1">1
				</label>
				<label class="btn btn-lg btn-primary">
					<input type="radio" name="lunch" value="2">2
				</label>
				<label class="btn btn-lg btn-primary active">
					<input type="radio" name="lunch" value="3" checked>3
				</label>
				<label class="btn btn-lg btn-primary">
					<input type="radio" name="lunch" value="4">4
				</label>
				<label class="btn btn-lg btn-primary">
					<input type="radio" name="lunch" value="5">5
				</label>
			</div>
			<br/>
			<a class="btn btn-lg btn-block btn-success" href="#dinner">Continue</a>
		</div>

		<div class="container paginate" style="padding-top: 70px; padding-bottom: 70px; text-align:center;" id="dinner">
			<h2>
				Dinner
			</h2>
			<div class="btn-grp" data-toggle="buttons">
				<label class="btn btn-lg btn-primary">
					<input type="radio" name="dinner" value="0">0
				</label>
				<label class="btn btn-lg btn-primary">
					<input type="radio" name="dinner" value="1">1
				</label>
				<label class="btn btn-lg btn-primary">
					<input type="radio" name="dinner" value="2">2
				</label>
				<label class="btn btn-lg btn-primary active">
					<input type="radio" name="dinner" value="3" checked>3
				</label>
				<label class="btn btn-lg btn-primary">
					<input type="radio" name="dinner" value="4">4
				</label>
				<label class="btn btn-lg btn-primary">
					<input type="radio" name="dinner" value="5">5
				</label>
			</div>
			<br/>
			<input type="submit" value="Submit" class="btn btn-lg btn-block btn-success">
		</div>
	</form>
	
{% endblock %}

rating/templates/rating/thankyou.html
{% extends "rating/base.html" %}

{% block title %}Mess Rating{% endblock %}

{% block css %}{% endblock %}

{% block js %}
	<script type="text/javascript">
		$( document ).ready(function() {
			setTimeout(function(){ window.location.href="{% url 'rating:start' %}" }, 4000);
		});
	</script>
{% endblock %}

{% block content %}
    <div class="container" style="padding-top:100px; text-align:center;">
        <h1>Thank you</h1>
        <h2>Redirecting. Please wait.</h2>
    </div>
{% endblock %}1